name: Release workoutrecorder-backend
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'App version to release'
        required: true
        default: '1.0.0'
  
jobs:
  release:
    name: Release workoutrecorder-backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 11
          maven-version: 3.8.2
          
      - name: Update pom.xml
        run: |
          version=${{ github.event.inputs.version }}
          sed -i "s/app-version/$version/g" pom.xml

      - name: Build and Package
        run: mvn clean package

      - name: Upload Release
        run: |
          aws s3 cp \
          target/workoutrecorder-backend-${{ github.event.inputs.version }}.jar \
          s3://red-devops-workout-recorder/release/workoutrecorder-backend-${{ github.event.inputs.version }}.jar
          